channels:
- conda-forge
dependencies:
- python=3.11.10
- pip<=24.2
- pip:
  - mlflow==3.1.0
  - cloudpickle==3.0.0
  - imbalanced-learn==0.13.0
  - numpy==1.26.4
  - pandas==1.5.3
  - psutil==5.9.0
  - scikit-learn==1.6.1
  - scipy==1.11.1
name: mlflow-env
